name: probashi
description: Inventory Management System.

version: 0.1.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  datetime_picker_formfield: ^2.0.0
  animated_splash_screen: ^1.1.0
  card_swiper: ^1.0.4
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.3
  double_back_to_close_app: ^2.1.0
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_launcher_icons: ^0.9.2
  form_field_validator: ^1.1.0
  horizontal_data_table: ^3.6.1+1
  
  get: ^4.3.8
  http: ^0.13.3
  image_picker: ^0.8.4
  intl: ^0.17.0
  mailer: ^5.0.2
  multi_image_picker: ^4.8.01
  # page_transition: ^2.0.1-nullsafety.0
  path: ^1.8.0
  path_provider: ^2.0.2

  percent_indicator: ^3.0.1
  permission_handler: ^8.3.0

  share: ^2.0.4
  shared_preferences: ^2.0.7
  
  sqflite: ^2.0.2

  # transparent_image: ^2.0.0
  uuid: ^3.0.4
  # weekday_selector: ^1.0.0
  date_field: ^2.1.2
  carousel_slider: ^4.0.0
  flutter_slidable: ^1.2.0
  get_storage: ^2.0.3
  number_to_words: ^1.0.0
  open_file: ^3.2.1
  pdf: ^3.7.1
  internet_connection_checker: ^0.0.1+3
  flutter_spinkit: ^5.1.0
  textfield_search: ^0.10.0
  searchfield: ^0.6.4
  flutter_typeahead: ^3.2.5

dev_dependencies:
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  # build_runner: ^2.1.7
  # hive_generator: ^1.1.2

flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#FE7900"
  #background_image: "assets/background.png"
  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing 
  # the leading # character.
  # The image parameter allows you to specify an image used in the splash screen.  It must be a 
  # png file and should be sized for 4x pixel density.
  image: assets/splash-logo.png

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or 
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  # The android, ios and web parameters can be used to disable generating a splash screen on a given 
  # platform.
  android: true
  ios: true
  web: true

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see 
  # https://developer.android.com/reference/android/view/Gravity): bottom, center, 
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: center
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see 
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill, 
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight, 
  # bottomLeft, or bottomRight.
  ios_content_mode: center
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web 
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s) 
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
  # To enable support for Android 12, set the following parameter to true.  Defaults to false.
  #android12: true

flutter:
  
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/logo.png
    - assets/prohealthhlogo.png
    - assets/doctorsignin.png
    - assets/patientsignin.png
    - assets/pharmalogo.png
    - assets/doctorimg.png
    - assets/apatient.png
    - assets/icons/doctor/
    - assets/icons/patient/
    - assets/splash-logo.png
    - assets/default.jpg
    - assets/patient.png
    - assets/images/fruit.jpeg
    - assets/fonts/

  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoeuil.ttf
          weight: 500
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600

    - family: SolaimanLipi
      fonts:
        - asset: assets/fonts/SolaimanLipi.ttf
          weight: 600

    - family: Shonar-Bangla
      fonts:
        - asset: assets/fonts/Shonar.ttf
          weight: 600
        - asset: assets/fonts/Shonarb.ttf
          weight: 700

    - family: Kalpurush
      fonts:
        - asset: assets/fonts/kalpurush.ttf
          weight: 600
       

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_launcher_name:
  name: "ProHealth"
